const categoryConstants = {
  CREATE_CATEGORY: "CREATE_CATEGORY",
  CREATE_CATEGORY_PENDING: "CREATE_CATEGORY_PENDING",
  CREATE_CATEGORY_FULFILLED: "CREATE_CATEGORY_FULFILLED",
  CREATE_CATEGORY_REJECTED: "CREATE_CATEGORY_REJECTED",

  DELETE_CATEGORY: "DELETE_CATEGORY",
  DELETE_CATEGORY_PENDING: "DELETE_CATEGORY_PENDING",
  DELETE_CATEGORY_FULFILLED: "DELETE_CATEGORY_FULFILLED",
  DELETE_CATEGORY_REJECTED: "DELETE_CATEGORY_REJECTED",

  FETCH_CATEGORIES: "FETCH_CATEGORIES",
  FETCH_CATEGORIES_PENDING: "FETCH_CATEGORIES_PENDING",
  FETCH_CATEGORIES_FULFILLED: "FETCH_CATEGORIES_FULFILLED",
  FETCH_CATEGORIES_REJECTED: "FETCH_CATEGORIES_REJECTED"
}

export default categoryConstants
