const documentConstants = {
  CREATE_DOCUMENT: "CREATE_DOCUMENT",

  DELETE_FILE: "DELETE_FILE",
  DELETE_FILE_PENDING: "DELETE_FILE_PENDING",
  DELETE_FILE_FULFILLED: "DELETE_FILE_FULFILLED",
  DELETE_FILE_REJECTED: "DELETE_FILE_REJECTED",

  FETCH_DOCUMENTS: "FETCH_DOCUMENTS",
  FETCH_DOCUMENTS_PENDING: "FETCH_DOCUMENTS_PENDING",
  FETCH_DOCUMENTS_FULFILLED: "FETCH_DOCUMENTS_FULFILLED",
  FETCH_DOCUMENTS_REJECTED: "FETCH_DOCUMENTS_REJECTED",

  FETCH_NEW_DOCUMENTS: "FETCH_NEW_DOCUMENTS",
  FETCH_NEW_DOCUMENTS_PENDING: "FETCH_NEW_DOCUMENTS_PENDING",
  FETCH_NEW_DOCUMENTS_FULFILLED: "FETCH_NEW_DOCUMENTS_FULFILLED",
  FETCH_NEW_DOCUMENTS_REJECTED: "FETCH_NEW_DOCUMENTS_REJECTED",

  UPLOAD_DOCUMENT: "UPLOAD_DOCUMENT",
  UPLOAD_DOCUMENT_PENDING: "UPLOAD_DOCUMENT_PENDING",
  UPLOAD_DOCUMENT_FULFILLED: "UPLOAD_DOCUMENT_FULFILLED",
  UPLOAD_DOCUMENT_REJECTED: "UPLOAD_DOCUMENT_REJECTED"
}

export default documentConstants
