const categoryConstants = {
  CREATE_FOLDER: "CREATE_FOLDER",
  CREATE_FOLDER_PENDING: "CREATE_FOLDER_PENDING",
  CREATE_FOLDER_FULFILLED: "CREATE_FOLDER_FULFILLED",
  CREATE_FOLDER_REJECTED: "CREATE_FOLDER_REJECTED",

  FETCH_FOLDERS: "FETCH_FOLDERS",
  FETCH_FOLDERS_PENDING: "FETCH_FOLDERS_PENDING",
  FETCH_FOLDERS_FULFILLED: "FETCH_FOLDERS_FULFILLED",
  FETCH_FOLDERS_REJECTED: "FETCH_FOLDERS_REJECTED",
}

export default categoryConstants
